CREATE TABLE AYUDAFORMULARIO(
    ID                  INTEGER NOT NULL AUTO_INCREMENT,
    INDICADOR_ID        INTEGER NOT NULL,
    AYUDA               VARCHAR(500),
    URL                 VARCHAR(600),
    PRIMARY KEY(ID)
);

/*REFERENCIA: AYUDAFORMULARIO-INDICADOR*/
ALTER TABLE AYUDAFORMULARIO ADD CONSTRAINT AYUDAFORMULARIO_INDICADOR_ID_FK FOREIGN KEY (INDICADOR_ID) REFERENCES INDICADOR (ID) ON DELETE CASCADE;
