
CREATE TEMPORARY TABLE TABLATEMPORAL(ID_INDICADOR INTEGER, SUBCOMPONENTE INTEGER, ID_TEXTO_MEJORA INTEGER, LIMITE_INFERIOR REAL(10,7), LIMITE_SUPERIOR REAL(10,7), TEXTO_MEJORA TEXT);

LOAD DATA LOCAL INFILE 'AYUDAXINDICADOR.csv' INTO TABLE TABLATEMPORAL
  FIELDS TERMINATED BY ','
  OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n' IGNORE 1 rows (ID_INDICADOR, SUBCOMPONENTE, ID_TEXTO_MEJORA, LIMITE_INFERIOR, LIMITE_SUPERIOR, TEXTO_MEJORA);

UPDATE AYUDAXINDICADOR
INNER JOIN TABLATEMPORAL on (TABLATEMPORAL.ID_INDICADOR = AYUDAXINDICADOR.ID_INDICADOR
AND TABLATEMPORAL.SUBCOMPONENTE = AYUDAXINDICADOR.SUBCOMPONENTE
AND TABLATEMPORAL.ID_TEXTO_MEJORA = AYUDAXINDICADOR.ID_TEXTO_MEJORA)
SET AYUDAXINDICADOR.TEXTO_MEJORA = TABLATEMPORAL.TEXTO_MEJORA;

DROP TEMPORARY TABLE TABLATEMPORAL;
