
CREATE TEMPORARY TABLE INDICADORESUPDATE (ID INTEGER, NOMBRE VARCHAR(200));

LOAD DATA LOCAL INFILE 'INDICADORES-UPDATE.csv' INTO TABLE INDICADORESUPDATE
  FIELDS TERMINATED BY ','
  OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n' IGNORE 1 rows (ID, NOMBRE);

UPDATE INDICADOR
INNER JOIN INDICADORESUPDATE on INDICADORESUPDATE.ID = INDICADOR.ID
SET INDICADOR.NOMBRE = INDICADORESUPDATE.NOMBRE;

DROP TEMPORARY TABLE INDICADORESUPDATE;
